DROP TABLE IF EXISTS AUTORES CASCADE;

CREATE TABLE AUTORES(
    AUT_ID INT ,
    AUT_NOME VARCHAR(100) ,
    AUT_PAIS VARCHAR(50) ,
	CONSTRAINT AUT_PK PRIMARY KEY(AUT_ID)

);

DROP TABLE IF EXISTS LIVROS CASCADE;
CREATE TABLE LIVROS(
    LIV_ISBN VARCHAR(13) ,
	LIV_AUT_ID INT ,
    LIV_TITULO VARCHAR(200) ,
    LIV_ANO INTEGER ,
	CONSTRAINT LIV_PK PRIMARY KEY(LIV_ISBN) ,
	CONSTRAINT LIV_AUT_FK FOREIGN KEY(LIV_AUT_ID) REFERENCES AUTORES(AUT_ID)
       ON DELETE RESTRICT ON UPDATE CASCADE

);

SELECT AUT.AUT_ID, AUT_NOME, AUT_PAIS
FROM AUTORES AUT
WHERE AUT.AUT_ID = 1;

SELECT AUTORES.*
FROM AUTORES;

SELECT LIV.LIV_ISBN , LIV_TITULO , LIV_ANO ,
       AUT.AUT_ID , AUT_NOME , AUT_PAIS
FROM LIVROS LIV INNER JOIN AUTORES AUT ON LIV.LIV_AUT_ID = AUT.AUT_ID
WHERE AUT.AUT_NOME LIKE %a%

UPDATE AUTORES SET
      AUT_NOME = 'marcos' ,
	  AUT_PAIS = 'França'
	  WHERE 
	  AUT_ID = 1;