DROP TABLE IF EXISTS RACAS CASCADE;

CREATE TABLE RACAS(
   RAC_ID INT ,
   RAC_NOME VARCHAR(50) ,
   RAC_CARACTERISTICAS VARCHAR(100),
   PRIMARY KEY(RAC_ID)

);






DROP TABLE IF EXISTS CACHORROS CASCADE;

CREATE TABLE CACHORROS(
     CAO_ID INT ,
	 CAO_RAC_ID INT ,
	 CAO_NOME VARCHAR(80) ,
	 PRIMARY KEY(CAO_ID) ,
	 FOREIGN KEY(CAO_RAC_ID) REFERENCES RACAS(RAC_ID) ON UPDATE CASCADE

);
