DROP TABLE IF EXISTS PRODUTOS CASCADE;

CREATE TABLE PRODUTOS(
    ITEM_NOME VARCHAR(30) ,
	ITEM_ID INT ,
	ITEM_PREÇO INT ,
	PRIMARY KEY (ITEM_ID)
);
SELECT ITEM.ITEM_ID , ITEM_NOME , ITEM_PREÇO
FROM PRODUTOS ITEM
WHERE ITEM.ITEM_ID = 2;