DROP TABLE IF EXISTS ARTISTAS CASCADE;
CREATE TABLE ARTISTAS(
 ART_ID INTEGER ,
 ART_NOME VARCHAR(100) ,
 ART_PAIS VARCHAR(50)
);

DROP TABLE IF EXISTS ALBUNS CASCADE;
CREATE TABLE ALBUNS(
ALB_ID VARCHAR(10),
ALB_TITULO VARCHAR(200) ,
ALB_ANO INTERGER ,
ALB_ART_ID INTERGER ,
 CONSTRAINT FK_ARTISTAS FOREIGN KEY (ALB_ART_ID) REFERENCES ARTISTAS(ART_ID)
);


